### ISSUE TITLE
apolloProvider.collect is not a function

### ISSUE THREAD

**Issue by hackuun** [Ethaan/vuexpresso#1]
I got empty page and condsole error

```
apolloProvider.collect is not a function
```

**Comment by Ethaan** [comment]
seems to be working for me, do you have a repo to take a look?

**Comment by Ethaan** [comment]
im closing this, please re-open if needed

**Comment by hackuun** [comment]
Sorry, I missed your answer. 

What repo you reffering to? I just clone your repo. Tried again,have the same error. Looks like I need additional setup which you don't mention.

**Comment by onezero11010** [comment]
Delete these lines,  It's work.
